### ISSUE TITLE
Add support for enabling `lifecycle {   prevent_destroy  = true   }` in the underlying resources

### ISSUE THREAD

**Issue by spkane** [nozaq/terraform-aws-remote-state-s3-backend#100]
Since you can't set   `lifecycle { prevent_destroy  = true }` on modules, it would be really nice if there was a variable that you could pass into the module which would enable this on critical resources that would cause a significant disruption is there were deleted, like the KMS key, bucket, etc.

**Comment by nozaq** [comment]
@spkane Thank you for your proposal :)

Terraform only accepts literal values for lifecycle settings ([official doc](https://www.terraform.io/language/meta-arguments/lifecycle#literal-values-only)), so unfortunately we can't easily switch them with variables.
Given that, we should implement own measures to prevent unintended deletions of critical resources. S3 buckets can only be deleted when you explicitly set `s3_bucket_force_destroy` to `true` since its default value set to `false` ([code](https://github.com/nozaq/terraform-aws-remote-state-s3-backend/blob/main/variables.tf#L135)). KMS keys don't have equivalent arguments, but you can set `kms_key_deletion_window_in_days` argument([code](https://github.com/nozaq/terraform-aws-remote-state-s3-backend/blob/main/variables.tf#L45)) to increase buffer and implement other detective controls to monitor keys which are being deleted.

Thanks again for your suggestion, hope this would help!
