### ISSUE TITLE
Can this module be used with multi-region KMS key for the primary and replica buckets?

### ISSUE THREAD

**Issue by lkolchin** [nozaq/terraform-aws-remote-state-s3-backend#45]
Terraform just recently released support for multi-Region primary KMS key in aws_kms_key resource.
Let's say you have your state bucket configured to use kms key in your main region.
I'm wondering if you can have your state replicated to a bucket in a different region that will be using kms key replica in the replica bucket config.

The idea is for both buckets to have kms encryption (therefore controlling user/role access to the statefiles in the bucket via kms permissions) and in case of one region going down you'd update the backend config and use this replica bucket with the replica kms key.
You'd also need additional dynamo table in the replica region...

Is there a support for such a config in your module?

Thanks.

**Comment by nozaq** [comment]
@lkolchin 
Replicating the state bucket into another region is supported, but the separated `aws_kms_key` is created for each region rather than creating multi-region keys. In case your main region goes down, you can use the replica bucket([this resource](https://github.com/nozaq/terraform-aws-remote-state-s3-backend/blob/main/outputs.tf#L11)) to restore your operation.

Regarding multi-region key support, currently I tend to stick with single-region keys since multi-region keys introduces additional security concerns([ref](https://docs.aws.amazon.com/kms/latest/developerguide/multi-region-keys-overview.html#mrk-when-to-use)) without clear benefit. When switching from the main bucket to the replica, you need to update both the bucket name and the kms key ARN in your backend config anyway.

**Comment by lkolchin** [comment]
Thanks @nozaq ,
I will need to play with your module a little bit.
Yeah that probably makes sense to use a separate kms key, now that I think about it :)

**Comment by nozaq** [comment]
@lkolchin You're welcome. Please let me know if you have other questions or concerns 👍🏼
