### ISSUE TITLE
Error: error deleting S3 bucket versioning (bucker-name): InvalidBucketState

### ISSUE THREAD

**Issue by RahilRehan** [nozaq/terraform-aws-remote-state-s3-backend#59]
When I run `terraform destroy`, I get this error

Error: error deleting S3 bucket versioning (bucket-name): InvalidBucketState: A replication configuration is present on this bucket, so you cannot change the versioning state. To change the versioning state, first delete the replication configuration.
│   status code: 409

however, when I run `terraform destroy` after 15 mins, the resources gets destroyed.

I couldn't get this resolved, any help? 

Thanks..

**Comment by nozaq** [comment]
@RahilRehan 
Thank you for reporting the issue!
I found that the bucket versioning can't be turned off when you have the replication configuration on the same bucket([AWS doc](https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication-and-other-bucket-configs.html#replication-and-versioning)).

> however, when I run terraform destroy after 15 mins, the resources gets destroyed.

It fails when `aws_s3_bucket_versioning` deletion ran before `aws_s3_bucket_replication_configuration`. 
Since terraform run resource deletions in parallel by default, the above case randomly occurrs.

I fixed this issue by making the bucket relication configuration dependent to the versioning configuration. Could you try v1.0.1?

**Comment by RahilRehan** [comment]
Thanks so much @nozaq , this worked!
